name: CD/CI Testing
on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    # Create Postgres instance
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails-test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://user:password@localhost:5432/rails-test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Install Nodejs (for Tailwind + DaisyUI)
      - name: Install Node.js dependencies
        run: npm install
      # Run migrations and create schema.rb file
      - name: Migrate DDBB
        run: bin/rails db:migrate
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Precompilar assets
      - name: Precompile assets
        run: bundle exec rake assets:precompile
      # Add or replace test runners here
      - name: Rails test
        run: bundle exec rails test
